# Generated by Django 5.0.1 on 2024-02-07 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristiquePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Latitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degre', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('seconde', models.IntegerField()),
                ('fuseau', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Longitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degre', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('seconde', models.IntegerField()),
                ('fuseau', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemDec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypePose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attribut1', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('caracteristique_points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeiTest.caracteristiquepoints')),
                ('latitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeiTest.latitude')),
                ('longitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeiTest.longitude')),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeiTest.photos')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeiTest.routes')),
                ('system_dec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeiTest.systemdec')),
                ('type_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeiTest.typeincident')),
                ('type_pose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeiTest.typepose')),
                ('type_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeiTest.typesystem')),
            ],
        ),
    ]
