# Generated by Django 5.0.1 on 2024-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeiTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eei',
            name='photos',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.RenameField(
            model_name='eei',
            old_name='attribut1',
            new_name='nom',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
