# Generated by Django 5.0.1 on 2024-02-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeiTest', '0002_alter_eei_photos_rename_attribut1_eei_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eei',
            old_name='caracteristique_points',
            new_name='caracteristique',
        ),
        migrations.RenameField(
            model_name='eei',
            old_name='photos',
            new_name='photo',
        ),
    ]
