# Generated by Django 5.0.1 on 2024-02-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeiTest', '0003_rename_caracteristique_points_eei_caracteristique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eei',
            name='type_system',
        ),
        migrations.AddField(
            model_name='systemdec',
            name='type_systeme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eeiTest.typesystem'),
        ),
    ]
