# Generated by Django 5.0.1 on 2024-02-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeiTest', '0004_remove_eei_type_system_systemdec_type_systeme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemdec',
            old_name='type_systeme',
            new_name='type_system',
        ),
        migrations.RemoveField(
            model_name='systemdec',
            name='nom',
        ),
    ]
