# Generated by Django 5.0.1 on 2024-02-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeiTest', '0005_rename_type_systeme_systemdec_type_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdec',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
